package com.csci.grammar; // Java Package generated by the BNF Converter.

import com.csci.visitor.Visitor;

public class EApp extends Exp {

    public String id_;
    public ListExp listexp_;

    public EApp(String p1, ListExp p2) {
        id_ = p1;
        listexp_ = p2;
    }

    @Override
    public String accept(Visitor visitor) {
        return visitor.visit(this);
    }

}
