package com.csci.grammar; // Java Package generated by the BNF Converter.

public class EApp extends Exp {

    public String id_;
    public ListExp listexp_;

    public EApp(String p1, ListExp p2) {
        id_ = p1;
        listexp_ = p2;
    }

}
