package com.csci.grammar; // Java Package generated by the BNF Converter.

public class EDouble extends Exp {

    public Double double_;

    public EDouble(Double p1) {
        double_ = p1;
    }

}
