package com.csci.grammar; // Java Package generated by the BNF Converter.

import com.csci.visitor.EvalVisitor;
import com.csci.visitor.PrintVisitor;

public class EFalse extends Exp {

    public EFalse() {
    }

    @Override
    public String accept(PrintVisitor visitor) {
        return visitor.visit(this);
    }

    @Override
    public Object eval(EvalVisitor visitor) throws Exception  {
        return visitor.visit(this);
    }
}
