package com.csci.grammar; // Java Package generated by the BNF Converter.

import com.csci.visitor.Visitor;

public class EFalse extends Exp {

    public EFalse() {
    }

    @Override
    public String accept(Visitor visitor) {
        return visitor.visit(this);
    }
}
