package com.csci.grammar; // Java Package generated by the BNF Converter.

import com.csci.visitor.Visitor;

public class EId extends Exp {

    public String id_;

    public EId(String p1) {
        id_ = p1;
    }

    @Override
    public String accept(Visitor visitor) {
        return visitor.visit(this);
    }

}
