package com.csci.grammar; // Java Package generated by the BNF Converter.

public class EInt extends Exp {

    public Integer integer_;

    public EInt(Integer p1) {
        integer_ = p1;
    }

}
