package com.csci.grammar; // Java Package generated by the BNF Converter.

import com.csci.visitor.EvalVisitor;
import com.csci.visitor.Visitable;
import com.csci.visitor.PrintVisitor;

public class EInt extends Exp implements Visitable {

    public Integer integer_;

    public EInt(Integer p1) {
        integer_ = p1;
    }

    @Override
    public String accept(PrintVisitor visitor) {
        return visitor.visit(this);
    }

    @Override
    public Object eval(EvalVisitor visitor) {
        return visitor.visit(this);
    }
}
