package com.csci.grammar; // Java Package generated by the BNF Converter.

import com.csci.visitor.EvalVisitor;
import com.csci.visitor.PrintVisitor;

public class ELt extends Exp {

    public Exp exp_1, exp_2;

    public ELt(Exp p1, Exp p2) {
        exp_1 = p1;
        exp_2 = p2;
    }

    @Override
    public String accept(PrintVisitor visitor) {
        return visitor.visit(this);
    }

    @Override
    public Object eval(EvalVisitor visitor) {
        return visitor.visit(this);
    }
}
