package com.csci.grammar; // Java Package generated by the BNF Converter.

public class ENEq extends Exp {

    public Exp exp_1, exp_2;

    public ENEq(Exp p1, Exp p2) {
        exp_1 = p1;
        exp_2 = p2;
    }

}
