package com.csci.grammar; // Java Package generated by the BNF Converter.

public class EOr extends Exp {

    public Exp exp_1, exp_2;

    public EOr(Exp p1, Exp p2) {
        exp_1 = p1;
        exp_2 = p2;
    }

}
