package com.csci.grammar; // Java Package generated by the BNF Converter.

import com.csci.visitor.Visitor;

public class EPIncr extends Exp {

    public Exp exp_;

    public EPIncr(Exp p1) {
        exp_ = p1;
    }

    @Override
    public String accept(Visitor visitor) {
        return visitor.visit(this);
    }

}
