package com.csci.grammar; // Java Package generated by the BNF Converter.

public class EString extends Exp {

    public String string_;

    public EString(String p1) {
        string_ = p1;
    }
}
