package com.csci.grammar; // Java Package generated by the BNF Converter.

public class ETyped extends Exp {

    public Exp exp_;
    public Type type_;

    public ETyped(Exp p1, Type p2) {
        exp_ = p1;
        type_ = p2;
    }
}
