package com.csci.grammar; // Java Package generated by the BNF Converter.

public class PDefs extends Program {

    public ListDef listdef_;

    public PDefs(ListDef p1) {
        listdef_ = p1;
    }

    @Override
    public String toString() {
        String functions = "";
        for (Def def : listdef_) {
            functions += def.toString();
        }
        return functions;
    }
}
