package com.csci.grammar; // Java Package generated by the BNF Converter.

public class SBlock extends Stm {

    public ListStm liststm_;

    public SBlock(ListStm p1) {
        liststm_ = p1;
    }

}
