package com.csci.grammar; // Java Package generated by the BNF Converter.

import com.csci.visitor.Visitor;

public class SDecls extends Stm {

    public Type type_;
    public ListId listid_;

    public SDecls(Type p1, ListId p2) {
        type_ = p1;
        listid_ = p2;
    }

    @Override
    public String accept(Visitor visitor) {
        return visitor.visit(this);
    }
}
