package com.csci.grammar; // Java Package generated by the BNF Converter.

import com.csci.visitor.Visitor;

public class SExp extends Stm {

    public Exp exp_;

    public SExp(Exp p1) {
        exp_ = p1;
    }
    @Override
    public String accept(Visitor visitor) {
        return visitor.visit(this);
    }

}
