package com.csci.grammar; // Java Package generated by the BNF Converter.

public class SIfElse extends Stm {

    public Exp exp_;

    public Stm stm_1, stm_2;

    public SIfElse(Exp p1, Stm p2, Stm p3) {
        exp_ = p1;
        stm_1 = p2;
        stm_2 = p3;
    }
}
