package com.csci.grammar; // Java Package generated by the BNF Converter.

import com.csci.visitor.EvalVisitor;
import com.csci.visitor.PrintVisitor;

public class SIfElse extends Stm {

    public Exp exp_;

    public ListStm stm_1, stm_2;

    public SIfElse(Exp p1, ListStm p2, ListStm p3) {
        exp_ = p1;
        stm_1 = p2;
        stm_2 = p3;
    }

    @Override
    public String accept(PrintVisitor visitor) {
        return visitor.visit(this);
    }

    @Override
    public void eval(EvalVisitor visitor) {
        visitor.visit(this);
    }
}
