package com.csci.grammar; // Java Package generated by the BNF Converter.

public class SInit extends Stm {

    public Type type_;
    public String id_;
    public Exp exp_;

    public SInit(Type p1, String p2, Exp p3) {
        type_ = p1;
        id_ = p2;
        exp_ = p3;
    }
}
