package com.csci.grammar; // Java Package generated by the BNF Converter.

import com.csci.visitor.Visitable;
import com.csci.visitor.Visitor;

public class SReturn extends Stm implements Visitable {

    public Exp exp_;

    public SReturn(Exp p1) {
        exp_ = p1;
    }

    @Override
    public String accept(Visitor visitor) {
        return visitor.visit(this);
    }
}
