package com.csci.grammar; // Java Package generated by the BNF Converter.

public class SWhile extends Stm {

    public Exp exp_;
    public Stm stm_;

    public SWhile(Exp p1, Stm p2) {
        exp_ = p1;
        stm_ = p2;
    }
}
