package com.csci.grammar; // Java Package generated by the BNF Converter.

import com.csci.visitor.Visitor;

public class SWhile extends Stm {

    public Exp exp_;
    public ListStm stm_;

    public SWhile(Exp p1, ListStm p2) {
        exp_ = p1;
        stm_ = p2;
    }

    @Override
    public String accept(Visitor visitor) {
        return visitor.visit(this);
    }
}
