package com.csci.grammar; // Java Package generated by the BNF Converter.

import com.csci.visitor.Visitor;

public class TypeInt extends Type {

    public TypeInt() { }

    @Override
    public String accept(Visitor visitor) {
        return visitor.visit(this);
    }
}
