package com.csci.grammar; // Java Package generated by the BNF Converter.

public class TypeInt extends Type {
    public TypeInt() {
    }

    @Override
    public String toString() {
        return "int";
    }
}
